# -*- coding: utf-8 -*-
"""fibanocci*series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQiC5MCOID0qjfykPWuY75GJ24eMlxQo
"""

def reqdlength(a):
  if(a == 0):
    return 0
  elif(a == 1):
    return 1
  else:
    return (reqdlength(a-1) + reqdlength(a-2))

a = int(input("Enter required length:"))

for b in range(a):
    print(reqdlength(b))