# -*- coding: utf-8 -*-
"""positive_number_in_range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19U2KQr1ef32eHriiXRo7-WueJppaDJy0
"""

list1 = [12,14,-2,100,-999,189,2,10,1,-1]
for i in list1:
  if i >= 0:
       print(i)